resources:
- name: concourse-example-app
  type: git
  source:
    uri: https://github.com/brianmmcclain/concourse-example-app
    branch: master
- name: app-staging
  type: cf
  source:
    api: api.v3.pcfdev.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: dev
    space: dev
    skip_cert_check: true

jobs:
- name: test-app
  plan:
  - get: concourse-example-app
    trigger: true
  - task: tests
    file: concourse-example-app/build.yml
  - put: app-staging
    params:
      manifest: ./concourse-example-app/manifest.yml

- name: hello-world
  plan:
  - get: concourse-example-app
    passed: [test-app]
    trigger: true
  - task: hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello World!"]
