resources:
- name: concourse-example-app
  type: git
  source:
    uri: https://github.com/brianmmcclain/concourse-example-app
    branch: srcclr
- name: app-staging
  type: cf
  source:
    api: api.bmcclain.com
    username: {{cf-username}}
    password: {{cf-password}}
    organization: stage
    space: stage
    skip_cert_check: true

jobs:
- name: test-app
  plan:
  - get: concourse-example-app
    trigger: true
  - task: tests
    file: concourse-example-app/ci/test.yml

- name: sourceclear-scan
  plan:
  - get: concourse-example-app
    passed: [test-app]
    trigger: true
  - task: srcclr-scan
    file: concourse-example-app/ci/sourceclear.yml
    params:
      SRCCLR_API_TOKEN: {{srcclr-api-token}}

- name: deploy-staging
  plan:
  - get: concourse-example-app
    passed: [sourceclear-scan]
    trigger: true
  - put: app-staging
    params:
      manifest: ./concourse-example-app/manifest.yml
